import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "../styles/globals.css";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600"], // 400=regular, 500=medium, 600=semibold
  variable: "--font-plus-jakarta-sans",
});

export const metadata: Metadata = {
  title: "UNIVISION: Idea Submission System",
  description: "Generated by EWSD-9",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
